// CT_PEER_REGISTER_REQ — SAN matching (RFC 5280 §4.2.1.6).
//
// Builds on test_register_cn_validation (CN-only matching) by
// exercising the SubjectAltName-based identity path:
//
//   san_client.crt — generated by gen_test_certs.sh — has:
//       CN  = tnetlib-generic
//       SAN = DNS:tnetlib-san-client, DNS:tnetlib-san-alias
//
// Cases:
//   1. Expected peer_name matches the primary SAN entry
//      (tnetlib-san-client) — accept, even though CN differs.
//   2. Expected peer_name matches the alias SAN
//      (tnetlib-san-alias) — accept, even though CN differs and
//      this isn't the first SAN in the list.
//   3. Expected peer_name doesn't match CN or any SAN — reject
//      with kRejectCnMismatch.

#include "../control_server.h"
#include "../control_session.h"
#include "../senders.h"
#include "../wire_codec.h"
#include "../services/fake_operator_auth_service.h"
#include "../services/fake_service_inventory.h"
#include "../services/peer_registry.h"

#include "fourstory/security/peer_security_gate.h"

#include "MessageId.h"

#include <boost/asio/buffer.hpp>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/detached.hpp>
#include <boost/asio/io_context.hpp>
#include <boost/asio/ip/tcp.hpp>
#include <boost/asio/read.hpp>
#include <boost/asio/ssl/context.hpp>
#include <boost/asio/ssl/stream.hpp>
#include <boost/asio/write.hpp>

#include <chrono>
#include <cstdio>
#include <cstring>
#include <string>
#include <thread>
#include <vector>

#ifndef TEST_CERT_DIR
#error "TEST_CERT_DIR must point at the tnetlib test cert fixtures"
#endif

namespace {

namespace asio = boost::asio;
using boost::asio::ip::tcp;
using tcontrolsvr::ControlServer;
using tcontrolsvr::ControlServerConfig;
using tcontrolsvr::FakeOperatorAuthService;
using tcontrolsvr::FakeServiceInventory;
using tcontrolsvr::PeerRegistry;
using tcontrolsvr::PacketHeader;
using tcontrolsvr::ComputeChecksum;
using tnetlib::protocol::MessageId;
using tnetlib::protocol::ToUint16;

int g_passed = 0;
int g_failed = 0;

void Check(bool ok, const char* label)
{
    if (ok) { ++g_passed; std::printf("  PASS  %s\n", label); }
    else    { ++g_failed; std::printf("  FAIL  %s\n", label); }
}

std::string CertPath(const char* file)
{
    return std::string(TEST_CERT_DIR) + "/" + file;
}

asio::ssl::context MakeServerCtx()
{
    asio::ssl::context ctx(asio::ssl::context::tls_server);
    ctx.set_options(
        asio::ssl::context::default_workarounds |
        asio::ssl::context::no_sslv2 |
        asio::ssl::context::no_sslv3 |
        asio::ssl::context::single_dh_use);
    ctx.use_certificate_file(CertPath("server.crt"),
                              asio::ssl::context::pem);
    ctx.use_private_key_file(CertPath("server.key"),
                              asio::ssl::context::pem);
    ctx.load_verify_file(CertPath("ca.crt"));
    ctx.set_verify_mode(asio::ssl::verify_peer |
                        asio::ssl::verify_fail_if_no_peer_cert);
    return ctx;
}

// Client context that presents wild_client.crt — CN=wild-generic,
// SAN=DNS:*.cluster.local (wildcard).
asio::ssl::context MakeWildClientCtx()
{
    asio::ssl::context ctx(asio::ssl::context::tls_client);
    ctx.set_options(
        asio::ssl::context::default_workarounds |
        asio::ssl::context::no_sslv2 |
        asio::ssl::context::no_sslv3);
    ctx.use_certificate_file(CertPath("wild_client.crt"),
                              asio::ssl::context::pem);
    ctx.use_private_key_file(CertPath("wild_client.key"),
                              asio::ssl::context::pem);
    ctx.load_verify_file(CertPath("ca.crt"));
    ctx.set_verify_mode(asio::ssl::verify_peer);
    return ctx;
}

// Client context that presents san_client.crt — CN=tnetlib-generic,
// SAN=tnetlib-san-client / tnetlib-san-alias.
asio::ssl::context MakeSanClientCtx()
{
    asio::ssl::context ctx(asio::ssl::context::tls_client);
    ctx.set_options(
        asio::ssl::context::default_workarounds |
        asio::ssl::context::no_sslv2 |
        asio::ssl::context::no_sslv3);
    ctx.use_certificate_file(CertPath("san_client.crt"),
                              asio::ssl::context::pem);
    ctx.use_private_key_file(CertPath("san_client.key"),
                              asio::ssl::context::pem);
    ctx.load_verify_file(CertPath("ca.crt"));
    ctx.set_verify_mode(asio::ssl::verify_peer);
    return ctx;
}

std::vector<std::byte>
BuildRegisterBody(std::uint32_t service_id)
{
    std::vector<std::byte> b;
    tcontrolsvr::wire::WritePOD<std::uint32_t>(b, service_id);
    tcontrolsvr::wire::WriteString(b, std::string("san-peer"));
    tcontrolsvr::wire::WriteString(b, std::string("127.0.0.1"));
    tcontrolsvr::wire::WritePOD<std::uint16_t>(b, 4000);
    tcontrolsvr::wire::WriteString(b, std::string("5.0.0-test"));
    tcontrolsvr::wire::WritePOD<std::uint32_t>(b, 1234);
    tcontrolsvr::wire::WritePOD<std::uint64_t>(b, 1700000000);
    return b;
}

template <class Stream>
void WriteFramed(Stream& s, std::uint16_t wId,
                  const std::vector<std::byte>& body)
{
    PacketHeader hdr{};
    hdr.wSize    = static_cast<std::uint16_t>(8 + body.size());
    hdr.wID      = wId;
    hdr.dwChkSum = ComputeChecksum(body.data(), body.size());
    asio::write(s, asio::buffer(&hdr, sizeof(hdr)));
    if (!body.empty())
        asio::write(s, asio::buffer(body.data(), body.size()));
}

struct Pkt {
    std::uint16_t wId = 0;
    std::vector<std::byte> body;
};

template <class Stream>
Pkt ReadFramed(Stream& s)
{
    PacketHeader hdr{};
    asio::read(s, asio::buffer(&hdr, sizeof(hdr)));
    Pkt p;
    p.wId = hdr.wID;
    const std::size_t body_len = hdr.wSize - sizeof(hdr);
    p.body.resize(body_len);
    if (body_len) asio::read(s, asio::buffer(p.body.data(), body_len));
    return p;
}

struct RegisterAck { std::uint8_t accepted; std::uint32_t reason; };
RegisterAck ParseRegisterAck(const std::vector<std::byte>& body)
{
    RegisterAck a{};
    if (body.size() < 1 + 4) return a;
    a.accepted = static_cast<std::uint8_t>(body[0]);
    std::memcpy(&a.reason, body.data() + 1, 4);
    return a;
}

enum class ClientCertKind { San, Wild };

RegisterAck DriveSanRegister(asio::ssl::context& server_ctx,
                              fourstory::security::PeerSecurityGate* gate,
                              std::uint32_t service_id,
                              ClientCertKind kind = ClientCertKind::San)
{
    asio::io_context io;
    FakeOperatorAuthService auth;
    FakeServiceInventory inv;
    tcontrolsvr::ServiceInstance svc{};
    svc.service_id = service_id;
    svc.group_id   = static_cast<std::uint8_t>((service_id >> 16) & 0xFF);
    svc.type_id    = static_cast<std::uint8_t>((service_id >>  8) & 0xFF);
    svc.server_id  = static_cast<std::uint8_t>(service_id & 0xFF);
    inv.AddService(svc);
    PeerRegistry peers(inv);

    ControlServerConfig svr_cfg{};
    svr_cfg.port      = 0;
    svr_cfg.auth      = &auth;
    svr_cfg.inventory = &inv;
    svr_cfg.peers     = &peers;
    svr_cfg.security  = gate;
    svr_cfg.ssl_ctx   = &server_ctx;
    ControlServer server(io, svr_cfg);
    asio::co_spawn(io, server.Run(), asio::detached);
    std::thread t([&io] { io.run(); });
    std::this_thread::sleep_for(std::chrono::milliseconds(50));

    asio::io_context client_io;
    auto client_ctx = (kind == ClientCertKind::Wild)
        ? MakeWildClientCtx() : MakeSanClientCtx();
    asio::ssl::stream<tcp::socket> stream(client_io, client_ctx);
    stream.next_layer().connect(
        tcp::endpoint(asio::ip::address_v4::loopback(), server.Port()));
    stream.handshake(asio::ssl::stream_base::client);

    WriteFramed(stream, ToUint16(MessageId::CT_PEER_REGISTER_REQ),
                BuildRegisterBody(service_id));
    auto ack_pkt = ReadFramed(stream);
    auto ack = ParseRegisterAck(ack_pkt.body);

    boost::system::error_code ig;
    stream.next_layer().close(ig);
    io.stop();
    t.join();
    return ack;
}

void TestSanPrimaryMatch()
{
    std::printf("[primary SAN entry matches → accept]\n");
    fourstory::security::SecurityConfig cfg;
    fourstory::security::PeerSecurityGate gate(cfg, nullptr);
    gate.InjectTrustForTest(1, 2, 3, "tnetlib-san-client");

    auto server_ctx = MakeServerCtx();
    const std::uint32_t service_id = (1u << 16) | (3u << 8) | 2u;
    auto ack = DriveSanRegister(server_ctx, &gate, service_id);
    Check(ack.accepted == 1,
          "REGISTER_ACK accepted=1 when expected matches primary SAN");
    Check(ack.reason == 0, "reason=0 on SAN match");
}

void TestSanAliasMatch()
{
    std::printf("[non-primary SAN entry (alias) matches → accept]\n");
    fourstory::security::SecurityConfig cfg;
    fourstory::security::PeerSecurityGate gate(cfg, nullptr);
    gate.InjectTrustForTest(1, 2, 3, "tnetlib-san-alias");

    auto server_ctx = MakeServerCtx();
    const std::uint32_t service_id = (1u << 16) | (3u << 8) | 2u;
    auto ack = DriveSanRegister(server_ctx, &gate, service_id);
    Check(ack.accepted == 1,
          "REGISTER_ACK accepted=1 when expected matches alias SAN");
}

void TestNoSanOrCnMatch()
{
    std::printf("[no CN/SAN match → reject]\n");
    fourstory::security::SecurityConfig cfg;
    fourstory::security::PeerSecurityGate gate(cfg, nullptr);
    // Expected is neither the CN ("tnetlib-generic") nor any SAN
    // ("tnetlib-san-client", "tnetlib-san-alias").
    gate.InjectTrustForTest(1, 2, 3, "some-totally-different-name");

    auto server_ctx = MakeServerCtx();
    const std::uint32_t service_id = (1u << 16) | (3u << 8) | 2u;
    auto ack = DriveSanRegister(server_ctx, &gate, service_id);
    Check(ack.accepted == 0,
          "REGISTER_ACK accepted=0 when no SAN/CN matches");
    Check(ack.reason == 3,
          "REGISTER_ACK reason=3 (kRejectCnMismatch)");
}

void TestCnFallbackStillWorks()
{
    std::printf("[CN match still accepted (regression of PR #47)]\n");
    fourstory::security::SecurityConfig cfg;
    fourstory::security::PeerSecurityGate gate(cfg, nullptr);
    // san_client.crt has CN = "tnetlib-generic". Expecting that
    // exact CN must still accept the connection even though SAN
    // matching is also available.
    gate.InjectTrustForTest(1, 2, 3, "tnetlib-generic");

    auto server_ctx = MakeServerCtx();
    const std::uint32_t service_id = (1u << 16) | (3u << 8) | 2u;
    auto ack = DriveSanRegister(server_ctx, &gate, service_id);
    Check(ack.accepted == 1,
          "REGISTER_ACK accepted=1 on CN match (SAN path didn't override)");
}

void TestWildcardSanMatchesSingleLabel()
{
    std::printf("[wildcard SAN matches single-label hostname]\n");
    fourstory::security::SecurityConfig cfg;
    fourstory::security::PeerSecurityGate gate(cfg, nullptr);
    // wild_client.crt has SAN=DNS:*.cluster.local. Expected name
    // "tlogin-eu-1.cluster.local" matches via RFC 6125 wildcard
    // expansion.
    gate.InjectTrustForTest(1, 2, 3, "tlogin-eu-1.cluster.local");

    auto server_ctx = MakeServerCtx();
    const std::uint32_t service_id = (1u << 16) | (3u << 8) | 2u;
    auto ack = DriveSanRegister(server_ctx, &gate, service_id,
                                 ClientCertKind::Wild);
    Check(ack.accepted == 1,
          "REGISTER_ACK accepted=1 on wildcard SAN match");
}

void TestWildcardSanRejectsDeepName()
{
    std::printf("[wildcard SAN rejects multi-label expansion]\n");
    fourstory::security::SecurityConfig cfg;
    fourstory::security::PeerSecurityGate gate(cfg, nullptr);
    // Multi-label name — RFC 6125 wildcard covers only ONE label,
    // so "deep.tlogin.cluster.local" must not match "*.cluster.local".
    gate.InjectTrustForTest(1, 2, 3, "deep.tlogin.cluster.local");

    auto server_ctx = MakeServerCtx();
    const std::uint32_t service_id = (1u << 16) | (3u << 8) | 2u;
    auto ack = DriveSanRegister(server_ctx, &gate, service_id,
                                 ClientCertKind::Wild);
    Check(ack.accepted == 0,
          "REGISTER_ACK accepted=0 on multi-label vs wildcard");
}

} // namespace

int main()
{
    std::printf("=== CT_PEER_REGISTER_REQ SAN validation ===\n");
    try
    {
        TestSanPrimaryMatch();
        TestSanAliasMatch();
        TestNoSanOrCnMatch();
        TestCnFallbackStillWorks();
        TestWildcardSanMatchesSingleLabel();
        TestWildcardSanRejectsDeepName();
    }
    catch (const std::exception& ex)
    {
        std::printf("  FAIL  exception thrown: %s\n", ex.what());
        ++g_failed;
    }
    std::printf("\nResults: %d passed, %d failed\n", g_passed, g_failed);
    return g_failed == 0 ? 0 : 1;
}
