$ErrorActionPreference = 'Stop'

# Generates MessageId.g.cs from ../../docs/packet-ids.csv.
# Run from anywhere; output goes next to this script.

$scriptDir = Split-Path $PSCommandPath -Parent
$csvPath = Resolve-Path (Join-Path $scriptDir '..\..\docs\packet-ids.csv')
$outPath = Join-Path $scriptDir 'MessageId.g.cs'

$rows = Import-Csv -Path $csvPath | Sort-Object IdDec, Name

# Group by numeric ID to detect aliases (same value, different name = legit C# enum aliases).
$grouped = $rows | Group-Object Id

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('// <auto-generated>')
[void]$sb.AppendLine('//   Generated by generate-messageid.ps1 from _rewrite/docs/packet-ids.csv.')
[void]$sb.AppendLine('//   Do NOT edit by hand. Re-run the script to regenerate.')
[void]$sb.AppendLine('// </auto-generated>')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace FourStory.Protocol;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('/// <summary>')
[void]$sb.AppendLine('/// All legacy <c>wMsgID</c> values across CS / MW / DM / SS / RW / CT / SM namespaces.')
[void]$sb.AppendLine('/// 9 numeric collisions exist (mostly REQ/ACK pairs sharing an ID) — they appear as enum aliases.')
[void]$sb.AppendLine('/// SM_* IDs are server-internal and never appear on the wire; included for completeness.')
[void]$sb.AppendLine('/// </summary>')
[void]$sb.AppendLine('public enum MessageId : ushort')
[void]$sb.AppendLine('{')

$lastBase = ''
foreach ($g in $grouped | Sort-Object { [int]$_.Group[0].IdDec }) {
    $idHex = $g.Group[0].Id
    foreach ($m in $g.Group) {
        if ($m.Base -ne $lastBase) {
            [void]$sb.AppendLine()
            [void]$sb.AppendLine("    // ===== $($m.Base) ($idHex+) =====")
            $lastBase = $m.Base
        }
        [void]$sb.AppendLine("    $($m.Name) = $idHex,")
    }
}

[void]$sb.AppendLine('}')

Set-Content -Path $outPath -Value $sb.ToString() -Encoding UTF8

$total = $rows.Count
$unique = $grouped.Count
"Wrote $outPath"
"  Total IDs: $total"
"  Unique values: $unique"
"  Aliases (collisions): $($total - $unique)"
