-- Mutable application state for the existing native Login service.
-- This is an empty modern schema, NOT an import or a repair of historical data.
-- No historical credentials, accounts, server addresses or player rows are seeded.
CREATE SCHEMA app_global;
REVOKE ALL ON SCHEMA app_global FROM PUBLIC;

-- Case-insensitive, accent-sensitive Unicode comparison plus explicit rtrim in
-- account lookup. This is a new application policy; exhaustive equivalence to
-- Latin1_General_CI_AS_KS and client code-page conversion remain import gates.
CREATE COLLATION app_global.account_name_ci
    (provider = icu, locale = 'und-u-ks-level2', deterministic = false);

CREATE TABLE app_global."TACCOUNT_PW" (
    "dwUserID" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "szUserID" varchar(50) COLLATE app_global.account_name_ci NOT NULL,
    "szPasswd" varchar(255),
    "dFirstLogin" timestamptz,
    "dLastLogin" timestamptz,
    CHECK (length(rtrim("szUserID")) > 0),
    CHECK ("szPasswd" IS NULL OR "szPasswd" ~ '^\$2[aby]\$[0-9]{2}\$[./A-Za-z0-9]{53}$')
);
CREATE UNIQUE INDEX account_login_name ON app_global."TACCOUNT_PW" (rtrim("szUserID"));
COMMENT ON TABLE app_global."TACCOUNT_PW" IS
    'New mutable accounts; bcrypt covers the unchanged client wire credential. No automatic historical credential conversion.';

CREATE TABLE app_global."TUSERINFOTABLE" (
    "dwUserID" integer PRIMARY KEY REFERENCES app_global."TACCOUNT_PW",
    "bCanCreateCharCount" smallint NOT NULL DEFAULT 6 CHECK ("bCanCreateCharCount" BETWEEN 0 AND 255),
    "bAgreement" smallint NOT NULL DEFAULT 0 CHECK ("bAgreement" BETWEEN 0 AND 255),
    "dwLastCharID" integer NOT NULL DEFAULT 0
);
COMMENT ON COLUMN app_global."TUSERINFOTABLE"."dwLastCharID" IS
    'Existing rewrite extension, not a recovered TUSERINFOTABLE column.';

CREATE TABLE app_global."TCURRENTUSER" (
    "dwKEY" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dwUserID" integer NOT NULL UNIQUE REFERENCES app_global."TACCOUNT_PW",
    "dwCharID" integer NOT NULL DEFAULT 0,
    "bGroupID" smallint NOT NULL DEFAULT 0 CHECK ("bGroupID" BETWEEN 0 AND 255),
    "bChannel" smallint NOT NULL DEFAULT 0 CHECK ("bChannel" BETWEEN 0 AND 255),
    "szIPAddr" varchar(50) NOT NULL DEFAULT '',
    "wPort" integer NOT NULL DEFAULT 0 CHECK ("wPort" BETWEEN 0 AND 65535),
    "bLocked" smallint NOT NULL DEFAULT 0 CHECK ("bLocked" IN (0,1)),
    "dLoginDate" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dEnterDate" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dwPcBangID" integer NOT NULL DEFAULT 0,
    "bLuckyNumber" smallint NOT NULL DEFAULT 0 CHECK ("bLuckyNumber" BETWEEN 0 AND 255),
    "szLoginIP" varchar(50) NOT NULL,
    "dwSiteCode" integer NOT NULL DEFAULT 0,
    "bChanneling" smallint NOT NULL DEFAULT 0 CHECK ("bChanneling" BETWEEN 0 AND 255)
);
CREATE INDEX current_user_group_channel ON app_global."TCURRENTUSER" ("bGroupID", "bChannel");
COMMENT ON TABLE app_global."TCURRENTUSER" IS
    'At most one live session per account. Session key identity is never reset or cycled; stale cleanup must match both account and key.';
COMMENT ON COLUMN app_global."TCURRENTUSER"."dwSiteCode" IS 'Rewrite extension preserving the complete wire DWORD bits.';

CREATE TABLE app_global."TLOG" (
    "dwKEY" integer PRIMARY KEY,
    "dwUserID" integer NOT NULL REFERENCES app_global."TACCOUNT_PW",
    "dwCharID" integer NOT NULL,
    "bGroupID" smallint NOT NULL CHECK ("bGroupID" BETWEEN 0 AND 255),
    "bChannel" smallint NOT NULL CHECK ("bChannel" BETWEEN 0 AND 255),
    "timeLOGIN" timestamptz NOT NULL,
    "timeLOGOUT" timestamptz NOT NULL
);
CREATE INDEX login_audit_account_time ON app_global."TLOG" ("dwUserID", "timeLOGIN");
COMMENT ON TABLE app_global."TLOG" IS
    'Durable session audit survives TCURRENTUSER deletion. New event times are timestamptz; historical dates are not converted.';
CREATE TABLE app_global."USERIPLOG" (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "IP" varchar(50) NOT NULL,
    "Username" varchar(50) NOT NULL,
    "Date_time" timestamptz NOT NULL
);
CREATE TABLE app_global."IPBLACKLIST_game" ("szIP" varchar(50) PRIMARY KEY);
CREATE TABLE app_global."TIPAUTHORITY" (
    "szIP" varchar(50) PRIMARY KEY,
    "bAuthority" smallint NOT NULL DEFAULT 0 CHECK ("bAuthority" BETWEEN 0 AND 255)
);
CREATE TABLE app_global."TUSERPROTECTED" (
    "dwSeq" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dwUserID" integer NOT NULL REFERENCES app_global."TACCOUNT_PW",
    "bBlockType" smallint NOT NULL CHECK ("bBlockType" BETWEEN 0 AND 255),
    "bEternal" smallint NOT NULL DEFAULT 0 CHECK ("bEternal" IN (0,1)),
    "startTime" timestamptz NOT NULL,
    "dwDuration" integer NOT NULL,
    "bBlockReason" smallint NOT NULL CHECK ("bBlockReason" BETWEEN 0 AND 255),
    "szComment" text NOT NULL,
    "szGMID" varchar(20) NOT NULL,
    "sentBanMail" smallint NOT NULL CHECK ("sentBanMail" IN (0,1))
);
CREATE INDEX user_protection_account ON app_global."TUSERPROTECTED" ("dwUserID");

-- Existing rewrite security/premium extensions; not fabricated historical rows.
CREATE TABLE app_global."TUSEREMAIL" (
    "dwUserID" integer PRIMARY KEY REFERENCES app_global."TACCOUNT_PW",
    "szEmail" text NOT NULL,
    "bTwoFactorEnabled" smallint NOT NULL DEFAULT 0 CHECK ("bTwoFactorEnabled" IN (0,1))
);
CREATE TABLE app_global."TUSERTRUSTEDIP" (
    "dwUserID" integer NOT NULL REFERENCES app_global."TACCOUNT_PW",
    "szIP" varchar(50) NOT NULL,
    PRIMARY KEY ("dwUserID", "szIP")
);
CREATE TABLE app_global."TSECURECODE" (
    "dwUserID" integer PRIMARY KEY REFERENCES app_global."TACCOUNT_PW",
    "strSecurityCode" varchar(55) NOT NULL,
    "bEnabled" integer NOT NULL CHECK ("bEnabled" IN (0,1)),
    "bTries" integer NOT NULL CHECK ("bTries" >= 0),
    "iLockTick" integer NOT NULL
);
CREATE TABLE app_global."TPCBANG" ("szIP" varchar(50) PRIMARY KEY, "szIPRange" varchar(50) NOT NULL);
CREATE TABLE app_global."TUSERPREMIUM" (
    "dwUserID" integer NOT NULL REFERENCES app_global."TACCOUNT_PW",
    "dwPremiumID" integer NOT NULL,
    "dtExpire" timestamptz NOT NULL,
    PRIMARY KEY ("dwUserID", "dwPremiumID")
);
CREATE TABLE app_global."TTESTLOGINUSER" ("dwuserid" integer PRIMARY KEY REFERENCES app_global."TACCOUNT_PW");

-- Lobby metadata and global character index projection needed by existing Login
-- queries. Character creation/world persistence is a later migration; empty means
-- no configured world or character, never an invented usable server endpoint.
CREATE TABLE app_global."TGROUP" (
    "bGroupID" smallint PRIMARY KEY CHECK ("bGroupID" BETWEEN 0 AND 255),
    "bType" smallint NOT NULL CHECK ("bType" BETWEEN 0 AND 255),
    "szNAME" varchar(50) NOT NULL,
    "bStatus" smallint NOT NULL DEFAULT 0 CHECK ("bStatus" BETWEEN 0 AND 255),
    "wBusy" integer NOT NULL DEFAULT 500 CHECK ("wBusy" BETWEEN 0 AND 65535),
    "wFull" integer NOT NULL DEFAULT 5000 CHECK ("wFull" BETWEEN 0 AND 65535),
    "dwMaxUser" integer NOT NULL DEFAULT 0
);
CREATE TABLE app_global."TCHANNEL" (
    "bGroupID" smallint NOT NULL REFERENCES app_global."TGROUP",
    "bChannel" smallint NOT NULL CHECK ("bChannel" BETWEEN 0 AND 255),
    "szNAME" varchar(50) NOT NULL,
    "bStatus" smallint NOT NULL DEFAULT 0 CHECK ("bStatus" BETWEEN 0 AND 255),
    "wBusy" integer NOT NULL DEFAULT 500 CHECK ("wBusy" BETWEEN 0 AND 65535),
    "wFull" integer NOT NULL DEFAULT 5000 CHECK ("wFull" BETWEEN 0 AND 65535),
    PRIMARY KEY ("bGroupID", "bChannel")
);
CREATE TABLE app_global."TSERVER" (
    "bGroupID" smallint NOT NULL CHECK ("bGroupID" BETWEEN 0 AND 255),
    "bServerID" smallint NOT NULL CHECK ("bServerID" BETWEEN 0 AND 255),
    "bType" smallint NOT NULL CHECK ("bType" BETWEEN 0 AND 255),
    "bMachineID" smallint NOT NULL CHECK ("bMachineID" BETWEEN 0 AND 255),
    "wPort" integer NOT NULL CHECK ("wPort" BETWEEN 0 AND 65535),
    PRIMARY KEY ("bGroupID", "bServerID", "bType")
);
CREATE TABLE app_global."TIPADDR" (
    "bMachineID" smallint NOT NULL CHECK ("bMachineID" BETWEEN 0 AND 255),
    "szIPAddr" varchar(50) NOT NULL,
    "bActive" smallint NOT NULL CHECK ("bActive" IN (0,1)),
    PRIMARY KEY ("bMachineID", "szIPAddr")
);
CREATE TABLE app_global."TMACHINE" (
    "bMachineID" smallint PRIMARY KEY CHECK ("bMachineID" BETWEEN 0 AND 255),
    "szNAME" varchar(50) NOT NULL,
    "bRouteID" integer NOT NULL DEFAULT 0
);
CREATE TABLE app_global."TALLCHARTABLE" (
    "dwUserID" integer NOT NULL REFERENCES app_global."TACCOUNT_PW",
    "bWorldID" smallint NOT NULL CHECK ("bWorldID" BETWEEN 0 AND 255),
    "dwCharID" integer NOT NULL,
    "bDelete" smallint NOT NULL DEFAULT 0 CHECK ("bDelete" IN (0,1)),
    PRIMARY KEY ("bWorldID", "dwCharID")
);
CREATE INDEX all_char_account ON app_global."TALLCHARTABLE" ("dwUserID", "bWorldID", "bDelete");
CREATE TABLE app_global."TRESERVEDNAME" ("szName" varchar(50) PRIMARY KEY);
CREATE TABLE app_global."TKEEPINGNAME" ("szName" varchar(50) PRIMARY KEY);
CREATE TABLE app_global."TVETERANCHART" (
    "bID" smallint PRIMARY KEY CHECK ("bID" BETWEEN 0 AND 255),
    "bLevel" smallint NOT NULL CHECK ("bLevel" BETWEEN 0 AND 255)
);

REVOKE ALL ON ALL TABLES IN SCHEMA app_global FROM PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA app_global FROM PUBLIC;
