-- Phase B development schema (Postgres dialect).
--
-- Curated from the MSSQL CSV dumps in _rewrite/docs/schema/. Only the
-- tables touched by the login server (Phase B service impls) are
-- defined here; the full game-DB schema lives in the legacy MSSQL.
--
-- This file is the dev-fixture used by tloginsvr_asio against a local
-- Postgres instance. Production targets MSSQL via SOCI's ODBC backend;
-- the column types map back losslessly (MSSQL tinyint → PG SMALLINT
-- is the only "widening" — values still round-trip).
--
-- Apply via:
--     psql -h localhost -U tloginsvr -d tloginsvr_dev -f postgres-dev.sql

-- ============================================================
-- TGLOBAL_RAGEZONE (login master DB)
-- ============================================================

-- Account master.
DROP TABLE IF EXISTS "TACCOUNT" CASCADE;
CREATE TABLE "TACCOUNT" (
    "dwUserID"    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "szUserID"    VARCHAR(50),
    "szPasswd"    VARCHAR(50),
    "bCheck"      SMALLINT NOT NULL DEFAULT 0,
    "dFirstLogin" TIMESTAMP,
    "dLastLogin"  TIMESTAMP
);
CREATE UNIQUE INDEX "IDX_TACCOUNT_szUserID" ON "TACCOUNT" ("szUserID");

-- Password storage (modern auth path uses this, not TACCOUNT.szPasswd).
DROP TABLE IF EXISTS "TACCOUNT_PW" CASCADE;
CREATE TABLE "TACCOUNT_PW" (
    "dwUserID"       INTEGER PRIMARY KEY,
    "szUserID"       VARCHAR(50) NOT NULL,
    "szPasswd"       VARCHAR(255),
    "bCheck"         SMALLINT NOT NULL DEFAULT 0,
    "dFirstLogin"    TIMESTAMP,
    "dLastLogin"     TIMESTAMP,
    "dwChanged"      INTEGER,
    "dwPWKey"        TEXT,
    "szRealUsername" VARCHAR(50),
    "szOrigin"       VARCHAR(4),
    "dwEMKey"        TEXT
);
CREATE UNIQUE INDEX "IDX_TACCOUNT_PW_szUserID" ON "TACCOUNT_PW" ("szUserID");

-- Live session directory. Inserted on LOGIN success, deleted on
-- terminator's Disconnect/ClientRequest, preserved on MapHandoff.
DROP TABLE IF EXISTS "TCURRENTUSER" CASCADE;
CREATE TABLE "TCURRENTUSER" (
    "dwKEY"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dwUserID"     INTEGER NOT NULL,
    "dwCharID"     INTEGER NOT NULL DEFAULT 0,
    "bGroupID"     SMALLINT NOT NULL DEFAULT 0,
    "bChannel"     SMALLINT NOT NULL DEFAULT 0,
    "szIPAddr"     VARCHAR(50),
    "wPort"        SMALLINT NOT NULL DEFAULT 0,
    "bLocked"      SMALLINT NOT NULL DEFAULT 0,
    "dLoginDate"   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dEnterDate"   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dwPcBangID"   INTEGER NOT NULL DEFAULT 0,
    "bLuckyNumber" SMALLINT NOT NULL DEFAULT 0,
    "szLoginIP"    VARCHAR(50) NOT NULL DEFAULT ''
);
CREATE INDEX "IDX_TCURRENTUSER_dwUserID" ON "TCURRENTUSER" ("dwUserID");

-- Audit log — INSERTed on login, timeLOGOUT UPDATEd on disconnect.
DROP TABLE IF EXISTS "TLOG" CASCADE;
CREATE TABLE "TLOG" (
    "dwKEY"      INTEGER PRIMARY KEY,
    "dwUserID"   INTEGER NOT NULL,
    "dwCharID"   INTEGER NOT NULL DEFAULT 0,
    "bGroupID"   SMALLINT NOT NULL DEFAULT 0,
    "bChannel"   SMALLINT NOT NULL DEFAULT 0,
    "timeLOGIN"  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "timeLOGOUT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Per-account agreement-acceptance flag for the EULA prompt.
DROP TABLE IF EXISTS "TUSERINFOTABLE" CASCADE;
CREATE TABLE "TUSERINFOTABLE" (
    "dwUserID"            INTEGER PRIMARY KEY,
    "bCanCreateCharCount" SMALLINT NOT NULL DEFAULT 6,
    "bAgreement"          SMALLINT NOT NULL DEFAULT 0,
    "dCabinetUse"         TIMESTAMP DEFAULT '2008-01-01',
    -- Last-played char (legacy TLogin SP m_dwCharID OUT). Stamped by
    -- TWorldSvr on map-server exit; read by SociAuthService on login
    -- to populate CS_LOGIN_ACK.dwCharID. Zero on first login.
    "dwLastCharID"        INTEGER NOT NULL DEFAULT 0
);

-- User-level bans (vs IP-level which is in IPBLACKLIST_game).
DROP TABLE IF EXISTS "TUSERPROTECTED" CASCADE;
CREATE TABLE "TUSERPROTECTED" (
    "dwSeq"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dwUserID"     INTEGER NOT NULL,
    "bBlockType"   SMALLINT NOT NULL,
    "bEternal"     SMALLINT NOT NULL DEFAULT 0,
    "bWorld"       SMALLINT,
    "dwCharID"     INTEGER,
    "szCharName"   VARCHAR(20),
    "startTime"    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dwDuration"   INTEGER NOT NULL DEFAULT 0,
    "bBlockReason" SMALLINT NOT NULL DEFAULT 0,
    "szComment"    VARCHAR(8000) NOT NULL DEFAULT '',
    "szGMID"       VARCHAR(20) NOT NULL DEFAULT '',
    "regDate"      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "sentBanMail"  SMALLINT NOT NULL DEFAULT 0
);
CREATE INDEX "IDX_TUSERPROTECTED_dwUserID" ON "TUSERPROTECTED" ("dwUserID");

-- IP banlist (game-server-side; the older IPBLACKLIST is legacy).
DROP TABLE IF EXISTS "IPBLACKLIST_game" CASCADE;
CREATE TABLE "IPBLACKLIST_game" (
    "szIP" VARCHAR(50) PRIMARY KEY
);

-- World groups.
DROP TABLE IF EXISTS "TGROUP" CASCADE;
CREATE TABLE "TGROUP" (
    "bGroupID"  SMALLINT PRIMARY KEY,
    "bType"     SMALLINT NOT NULL DEFAULT 0,
    "szNAME"    VARCHAR(50) NOT NULL,
    "szDSN"     VARCHAR(50) NOT NULL DEFAULT '',
    "szUserID"  VARCHAR(50) NOT NULL DEFAULT '',
    "szPasswd"  VARCHAR(255),
    "wFull"     SMALLINT NOT NULL DEFAULT 5000,
    "wBusy"     SMALLINT NOT NULL DEFAULT 500,
    "dwMaxUser" INTEGER NOT NULL DEFAULT 0,
    "bUseRate"  SMALLINT NOT NULL DEFAULT 1,
    "bStatus"   SMALLINT NOT NULL DEFAULT 0
);

-- Per-group channels.
DROP TABLE IF EXISTS "TCHANNEL" CASCADE;
CREATE TABLE "TCHANNEL" (
    "bGroupID" SMALLINT NOT NULL,
    "bChannel" SMALLINT NOT NULL,
    "szNAME"   VARCHAR(50) NOT NULL,
    "wFull"    SMALLINT NOT NULL DEFAULT 5000,
    "wBusy"    SMALLINT NOT NULL DEFAULT 500,
    "bStatus"  SMALLINT NOT NULL DEFAULT 0,
    PRIMARY KEY ("bGroupID", "bChannel")
);

-- Map / world server registry.
DROP TABLE IF EXISTS "TSERVER" CASCADE;
CREATE TABLE "TSERVER" (
    "bGroupID"   SMALLINT NOT NULL,
    "bServerID"  SMALLINT NOT NULL,
    "bType"      SMALLINT NOT NULL,
    "bMachineID" SMALLINT NOT NULL,
    "wPort"      SMALLINT NOT NULL,
    "szName"     VARCHAR(50) NOT NULL DEFAULT ''
);
CREATE INDEX "IDX_TSERVER_group_type" ON "TSERVER" ("bGroupID", "bType");

-- Machine → public-IP map. Joined with TSERVER to resolve the wire-
-- visible endpoint for CS_START_ACK.
DROP TABLE IF EXISTS "TIPADDR" CASCADE;
CREATE TABLE "TIPADDR" (
    "bMachineID" SMALLINT NOT NULL,
    "szIPAddr"   VARCHAR(50) NOT NULL,
    "szPriAddr"  VARCHAR(50) NOT NULL DEFAULT '',
    "bActive"    SMALLINT NOT NULL DEFAULT 1,
    PRIMARY KEY ("bMachineID", "szIPAddr")
);

-- Veteran-bonus thresholds (CS_VETERAN_REQ reads top 3 rows).
DROP TABLE IF EXISTS "TVETERANCHART" CASCADE;
CREATE TABLE "TVETERANCHART" (
    "bID"    SMALLINT PRIMARY KEY,
    "bLevel" SMALLINT NOT NULL
);

-- ============================================================
-- TGAME_RAGEZONE (game/world — subset for char service)
-- ============================================================

-- Per-world char records.
DROP TABLE IF EXISTS "TCHARTABLE" CASCADE;
CREATE TABLE "TCHARTABLE" (
    "dwCharID"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dwUserID"          INTEGER NOT NULL,
    "bSlot"             SMALLINT NOT NULL,
    "szNAME"            VARCHAR(50) NOT NULL,
    "bStartAct"         SMALLINT NOT NULL DEFAULT 0,
    "bClass"            SMALLINT NOT NULL,
    "bRace"             SMALLINT NOT NULL,
    "bCountry"          SMALLINT NOT NULL,
    "bRealSex"          SMALLINT NOT NULL,
    "bSex"              SMALLINT NOT NULL,
    "bHair"             SMALLINT NOT NULL,
    "bFace"             SMALLINT NOT NULL,
    "bBody"             SMALLINT NOT NULL,
    "bPants"            SMALLINT NOT NULL,
    "bHand"             SMALLINT NOT NULL,
    "bFoot"             SMALLINT NOT NULL,
    "bHelmetHide"       SMALLINT NOT NULL DEFAULT 0,
    "bLevel"            SMALLINT NOT NULL DEFAULT 1,
    "dwEXP"             INTEGER  NOT NULL DEFAULT 0,
    "dwHP"              INTEGER  NOT NULL DEFAULT 50,
    "dwMP"              INTEGER  NOT NULL DEFAULT 30,
    "wSkillPoint"       SMALLINT NOT NULL DEFAULT 0,
    "dwRegion"          INTEGER  NOT NULL DEFAULT 0,
    "dwGold"            INTEGER  NOT NULL DEFAULT 0,
    "dwSilver"          INTEGER  NOT NULL DEFAULT 0,
    "dwCooper"          INTEGER  NOT NULL DEFAULT 0,
    "bGuildLeave"       SMALLINT NOT NULL DEFAULT 0,
    "dwGuildLeaveTime"  INTEGER  NOT NULL DEFAULT 0,
    "wMapID"            SMALLINT NOT NULL DEFAULT 2010,
    "wSpawnID"          SMALLINT NOT NULL DEFAULT 15003,
    "wLastSpawnID"      SMALLINT NOT NULL DEFAULT 15003,
    "wTemptedMon"       SMALLINT NOT NULL DEFAULT 0,
    "bAftermath"        SMALLINT NOT NULL DEFAULT 0,
    "fPosX"             REAL NOT NULL DEFAULT 3664.405,
    "fPosY"             REAL NOT NULL DEFAULT 86.16578,
    "fPosZ"             REAL NOT NULL DEFAULT 557.2542,
    "wDIR"              SMALLINT NOT NULL DEFAULT 762,
    "dwRankPoint"       INTEGER NOT NULL DEFAULT 0,
    "bDelete"           SMALLINT NOT NULL DEFAULT 0,
    "dCreateDate"       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dDeleteDate"       TIMESTAMP,
    "dwLastDestination" INTEGER NOT NULL DEFAULT 0,
    "bOriCountry"       SMALLINT NOT NULL DEFAULT 4,
    "dLogoutDate"       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX "IDX_TCHARTABLE_user_slot" ON "TCHARTABLE" ("dwUserID", "bSlot");
CREATE UNIQUE INDEX "IDX_TCHARTABLE_name_alive" ON "TCHARTABLE" ("szNAME")
    WHERE "bDelete" = 0;

-- Cross-world char index — global name uniqueness + char-count
-- bookkeeping.
DROP TABLE IF EXISTS "TALLCHARTABLE" CASCADE;
CREATE TABLE "TALLCHARTABLE" (
    "dwSeq"       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "dwUserID"    INTEGER NOT NULL,
    "bWorldID"    SMALLINT NOT NULL,
    "dwCharID"    INTEGER NOT NULL,
    "bSlot"       SMALLINT NOT NULL,
    "szName"      VARCHAR(50) NOT NULL,
    "bClass"      SMALLINT NOT NULL,
    "bRace"       SMALLINT NOT NULL,
    "bCountry"    SMALLINT NOT NULL,
    "bSex"        SMALLINT NOT NULL,
    "bHair"       SMALLINT NOT NULL,
    "bFace"       SMALLINT NOT NULL,
    "bBody"       SMALLINT NOT NULL,
    "bPants"      SMALLINT NOT NULL,
    "bHand"       SMALLINT NOT NULL,
    "bFoot"       SMALLINT NOT NULL,
    "bLevel"      SMALLINT NOT NULL,
    "dwEXP"       INTEGER  NOT NULL,
    "bDelete"     SMALLINT NOT NULL DEFAULT 0,
    "dCreateDate" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "dDeleteDate" TIMESTAMP,
    "dwPlayTime"  INTEGER  NOT NULL DEFAULT 0,
    "dwGold"      INTEGER  NOT NULL DEFAULT 0,
    "dwSilver"    INTEGER  NOT NULL DEFAULT 0,
    "dwCooper"    INTEGER  NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX "IDX_TALLCHARTABLE_name_alive" ON "TALLCHARTABLE" ("szName")
    WHERE "bDelete" = 0;
CREATE INDEX "IDX_TALLCHARTABLE_user_world" ON "TALLCHARTABLE" ("dwUserID", "bWorldID");

-- GM-reserved character names (delete-protected).
DROP TABLE IF EXISTS "TKEEPINGNAME" CASCADE;
CREATE TABLE "TKEEPINGNAME" (
    "dwSeq"  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "szName" VARCHAR(100) NOT NULL
);
CREATE UNIQUE INDEX "IDX_TKEEPINGNAME_name" ON "TKEEPINGNAME" ("szName");

-- Per-user reserved names (used in CREATECHAR validation).
DROP TABLE IF EXISTS "TRESERVEDNAME" CASCADE;
CREATE TABLE "TRESERVEDNAME" (
    "szName"   VARCHAR(50) PRIMARY KEY,
    "dwUserID" INTEGER NOT NULL
);

-- Guild membership (joined for fame display in CHARLIST).
DROP TABLE IF EXISTS "TGUILDMEMBERTABLE" CASCADE;
CREATE TABLE "TGUILDMEMBERTABLE" (
    "dwCharID"  INTEGER PRIMARY KEY,
    "dwGuildID" INTEGER NOT NULL,
    "bDuty"     SMALLINT NOT NULL DEFAULT 0,
    "bPeer"     SMALLINT NOT NULL DEFAULT 0,
    "dwService" INTEGER  NOT NULL DEFAULT 0
);
CREATE INDEX "IDX_TGUILDMEMBERTABLE_guild" ON "TGUILDMEMBERTABLE" ("dwGuildID");

-- Guild master record (fame/level shown next to chars in CHARLIST).
DROP TABLE IF EXISTS "TGUILDTABLE" CASCADE;
CREATE TABLE "TGUILDTABLE" (
    "dwID"        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "szName"      VARCHAR(50) NOT NULL,
    "dwChief"     INTEGER NOT NULL,
    "bLevel"      SMALLINT NOT NULL DEFAULT 0,
    "dwFame"      INTEGER NOT NULL DEFAULT 0,
    "dwFameColor" INTEGER NOT NULL DEFAULT 0
);

-- BR shard membership (CS_START_REQ override route to ServerID=50).
DROP TABLE IF EXISTS "TBRPLAYERTABLE" CASCADE;
CREATE TABLE "TBRPLAYERTABLE" (
    "dwCharID" INTEGER PRIMARY KEY,
    "dwUserID" INTEGER NOT NULL
);

-- BOW (Battle of Worlds) shard membership — same shape as BR.
-- Override route to ServerID=30 if (user, char) matches.
DROP TABLE IF EXISTS "TBOWPLAYERTABLE" CASCADE;
CREATE TABLE "TBOWPLAYERTABLE" (
    "dwCharID" INTEGER PRIMARY KEY,
    "dwUserID" INTEGER NOT NULL
);

-- Equipped-item slot for CHARLIST display (subset of TITEMTABLE).
DROP TABLE IF EXISTS "TITEMTABLE" CASCADE;
CREATE TABLE "TITEMTABLE" (
    "dlID"          BIGINT PRIMARY KEY,
    "bStorageType"  SMALLINT NOT NULL,
    "dwStorageID"   INTEGER  NOT NULL,
    "bOwnerType"    SMALLINT NOT NULL,
    "dwOwnerID"     INTEGER  NOT NULL,
    "bItemID"       SMALLINT NOT NULL,
    "wItemID"       SMALLINT NOT NULL,
    "bLevel"        SMALLINT NOT NULL,
    "bCount"        SMALLINT NOT NULL DEFAULT 1,
    "bGradeEffect"  SMALLINT NOT NULL DEFAULT 0,
    "wMoggItemID"   SMALLINT NOT NULL DEFAULT 0
);
CREATE INDEX "IDX_TITEMTABLE_owner" ON "TITEMTABLE"
    ("bStorageType", "dwStorageID", "bOwnerType", "dwOwnerID");

-- ============================================================
-- Premium / PC-Bang side tables — populated by the legacy TLogin SP
-- final-block lookups. Both are optional; SociAuthService catches the
-- "missing table" exception and returns 0 for the corresponding fields
-- so deployments that don't care about PC-Bang or premium tiers can
-- skip applying these tables entirely.
-- ============================================================

-- PC-Bang (Korean / TW gaming-cafe) IP whitelist. The legacy SP matches
-- a peer IP against either an exact entry or a SQL LIKE pattern
-- (`192.168.%`). We keep both columns so operators can choose the form
-- per region.
DROP TABLE IF EXISTS "TPCBANG" CASCADE;
CREATE TABLE "TPCBANG" (
    "szIP"      VARCHAR(40),         -- exact match
    "szIPRange" VARCHAR(40),         -- SQL LIKE pattern, e.g. "192.168.%"
    "szName"    VARCHAR(64)
);
CREATE INDEX "IDX_TPCBANG_szIP" ON "TPCBANG" ("szIP");

-- Active premium tier per user. Legacy TLogin SP returns the highest
-- non-expired dwPremiumID — we mirror that via ORDER BY dwPremiumID DESC
-- LIMIT 1 in SociAuthService. Multiple rows per user are allowed
-- (different products / billing windows) so the unique constraint is
-- composite.
DROP TABLE IF EXISTS "TUSERPREMIUM" CASCADE;
CREATE TABLE "TUSERPREMIUM" (
    "dwUserID"    INTEGER  NOT NULL,
    "dwPremiumID" INTEGER  NOT NULL,
    "dtStart"     TIMESTAMP,
    "dtExpire"    TIMESTAMP NOT NULL,
    PRIMARY KEY ("dwUserID", "dwPremiumID")
);
CREATE INDEX "IDX_TUSERPREMIUM_user" ON "TUSERPREMIUM" ("dwUserID", "dtExpire");
