// End-to-end TLS round-trip for TlsAsioSession.
//
// Cert fixtures (CA + server + client) are generated by
// gen_test_certs.sh at CMake configure time. Their paths are baked
// into the test binary via -D macros so the test runs straight from
// `ctest` with no environment plumbing.
//
// What this test exercises:
//   * Mutual TLS handshake (server verifies client cert, client verifies
//     server cert, both via the project test CA)
//   * Full packet codec on top of the TLS stream — same XOR + checksum
//     + sequence numbers as the plain AsioSession path
//   * Bidirectional traffic (client sends, server echoes back)
//   * Concurrent SendPacket from multiple producer coroutines (proves
//     the per-session send queue carried over to the TLS variant)
//
// What it does NOT exercise (deferred to follow-up PRs):
//   * Cert revocation (CRL/OCSP)
//   * Cert rotation without restart
//   * Negative paths (untrusted CA, expired cert, wrong CN)
//   * SSL_CTX share across many sessions

#include "../TNetLib/tls_asio_session.h"

#include <boost/asio/io_context.hpp>
#include <boost/asio/co_spawn.hpp>
#include <boost/asio/detached.hpp>
#include <boost/asio/post.hpp>
#include <boost/asio/redirect_error.hpp>
#include <boost/asio/use_awaitable.hpp>
#include <boost/asio/ip/tcp.hpp>
#include <boost/asio/ssl/context.hpp>

#include <atomic>
#include <chrono>
#include <cstdio>
#include <cstring>
#include <memory>
#include <mutex>
#include <thread>
#include <vector>

#ifndef TEST_CERT_DIR
#error "TEST_CERT_DIR must be defined to the path of the test cert fixtures"
#endif

namespace asio = boost::asio;
using boost::asio::ip::tcp;

namespace {

int g_passed = 0;
int g_failed = 0;

void Check(bool ok, const char* label)
{
    if (ok) { ++g_passed; std::printf("  PASS  %s\n", label); }
    else    { ++g_failed; std::printf("  FAIL  %s\n", label); }
}

std::string CertPath(const char* file)
{
    return std::string(TEST_CERT_DIR) + "/" + file;
}

// Server-side SSL_CTX: present server.crt, demand a client cert
// signed by the test CA.
asio::ssl::context MakeServerCtx()
{
    asio::ssl::context ctx(asio::ssl::context::tls_server);
    ctx.set_options(
        asio::ssl::context::default_workarounds |
        asio::ssl::context::no_sslv2 |
        asio::ssl::context::no_sslv3 |
        asio::ssl::context::single_dh_use);
    ctx.use_certificate_file(CertPath("server.crt"),
                              asio::ssl::context::pem);
    ctx.use_private_key_file(CertPath("server.key"),
                              asio::ssl::context::pem);
    ctx.load_verify_file(CertPath("ca.crt"));
    ctx.set_verify_mode(asio::ssl::verify_peer |
                        asio::ssl::verify_fail_if_no_peer_cert);
    return ctx;
}

// Client-side SSL_CTX: present client.crt, verify the server's cert
// chains to the test CA.
asio::ssl::context MakeClientCtx()
{
    asio::ssl::context ctx(asio::ssl::context::tls_client);
    ctx.set_options(
        asio::ssl::context::default_workarounds |
        asio::ssl::context::no_sslv2 |
        asio::ssl::context::no_sslv3);
    ctx.use_certificate_file(CertPath("client.crt"),
                              asio::ssl::context::pem);
    ctx.use_private_key_file(CertPath("client.key"),
                              asio::ssl::context::pem);
    ctx.load_verify_file(CertPath("ca.crt"));
    ctx.set_verify_mode(asio::ssl::verify_peer);
    return ctx;
}

void TestTlsPacketRoundtrip()
{
    std::printf("[TLS packet round-trip via TlsAsioSession]\n");

    asio::io_context io;
    auto server_ctx = MakeServerCtx();
    auto client_ctx = MakeClientCtx();

    tcp::acceptor acceptor(io,
        tcp::endpoint(tcp::v4(), 0));
    const std::uint16_t port = acceptor.local_endpoint().port();
    Check(port != 0, "listener bound");

    // Server side — accept one connection, run RunPackets, echo each
    // packet back at the codec level.
    std::atomic<int> server_accepted{0};
    asio::co_spawn(io,
        [&]() -> asio::awaitable<void> {
            boost::system::error_code ec;
            auto sock = co_await acceptor.async_accept(
                asio::redirect_error(asio::use_awaitable, ec));
            if (ec) co_return;

            auto sess = std::make_shared<tnetlib::TlsAsioSession>(
                std::move(sock), server_ctx);
            const bool hs_ok = co_await sess->Handshake(
                tnetlib::TlsRole::Server);
            if (!hs_ok) co_return;
            server_accepted.fetch_add(1);

            auto sess_for_echo = sess;
            co_await sess->RunPackets(
                [sess_for_echo](const tnetlib::DecodedPacket& pkt) {
                    std::vector<std::byte> body_copy(
                        pkt.body.begin(), pkt.body.end());
                    const std::uint16_t wId = pkt.wId;
                    asio::co_spawn(
                        sess_for_echo->Stream().get_executor(),
                        [sess_for_echo, wId,
                         body_copy = std::move(body_copy)]()
                            -> asio::awaitable<void> {
                            co_await sess_for_echo->SendPacket(wId,
                                std::span<const std::byte>(
                                    body_copy.data(), body_copy.size()));
                        },
                        asio::detached);
                });
        },
        asio::detached);

    std::thread io_thread([&io] { io.run(); });
    std::this_thread::sleep_for(std::chrono::milliseconds(50));

    // Client side — connect a raw socket, hand it to TlsAsioSession,
    // drive the client-side handshake, then run a packet round-trip.
    asio::io_context client_io;
    tcp::socket client_sock(client_io);
    client_sock.connect(tcp::endpoint(asio::ip::address_v4::loopback(), port));
    Check(client_sock.is_open(), "client socket connected");

    auto client_sess = std::make_shared<tnetlib::TlsAsioSession>(
        std::move(client_sock), client_ctx);

    std::atomic<bool> hs_done{false};
    std::atomic<bool> hs_ok{false};
    asio::co_spawn(client_io,
        [client_sess, &hs_done, &hs_ok]() -> asio::awaitable<void> {
            const bool ok = co_await client_sess->Handshake(
                tnetlib::TlsRole::Client);
            hs_ok.store(ok);
            hs_done.store(true);
        },
        asio::detached);

    std::vector<std::pair<std::uint16_t, std::vector<std::byte>>> received;
    std::atomic<int> received_count{0};
    asio::co_spawn(client_io,
        [client_sess, &received, &received_count, &hs_done]()
            -> asio::awaitable<void> {
            // Wait for client-side handshake to finish before reading.
            // In a real caller this would be ordered by co_await chain;
            // we keep the test linear-ish by polling hs_done.
            while (!hs_done.load())
                co_await asio::post(asio::use_awaitable);
            co_await client_sess->RunPackets(
                [&received, &received_count](
                    const tnetlib::DecodedPacket& pkt) {
                    received.push_back({
                        pkt.wId,
                        std::vector<std::byte>(pkt.body.begin(),
                                                pkt.body.end())});
                    received_count.fetch_add(1);
                });
        },
        asio::detached);

    asio::co_spawn(client_io,
        [client_sess, &hs_done]() -> asio::awaitable<void> {
            while (!hs_done.load())
                co_await asio::post(asio::use_awaitable);
            const char* p1 = "tls-hello";
            const char* p2 = "tls-world";
            const char* p3 = "tls-done!";
            co_await client_sess->SendPacket(0x3001,
                std::span<const std::byte>(
                    reinterpret_cast<const std::byte*>(p1), 9));
            co_await client_sess->SendPacket(0x3002,
                std::span<const std::byte>(
                    reinterpret_cast<const std::byte*>(p2), 9));
            co_await client_sess->SendPacket(0x3003,
                std::span<const std::byte>(
                    reinterpret_cast<const std::byte*>(p3), 9));
        },
        asio::detached);

    std::thread client_thread([&client_io] { client_io.run(); });

    const auto deadline = std::chrono::steady_clock::now() +
                          std::chrono::seconds(5);
    while (received_count.load() < 3 &&
           std::chrono::steady_clock::now() < deadline)
    {
        std::this_thread::sleep_for(std::chrono::milliseconds(20));
    }

    Check(hs_ok.load(), "client TLS handshake succeeded");
    Check(server_accepted.load() == 1, "server accepted one connection");
    Check(received.size() == 3, "client received all three echoed packets");
    if (received.size() == 3)
    {
        Check(received[0].first == 0x3001 &&
              received[0].second.size() == 9 &&
              std::memcmp(received[0].second.data(), "tls-hello", 9) == 0,
              "packet 0 wId + body match");
        Check(received[1].first == 0x3002 &&
              received[1].second.size() == 9 &&
              std::memcmp(received[1].second.data(), "tls-world", 9) == 0,
              "packet 1 wId + body match");
        Check(received[2].first == 0x3003 &&
              received[2].second.size() == 9 &&
              std::memcmp(received[2].second.data(), "tls-done!", 9) == 0,
              "packet 2 wId + body match");
        Check(client_sess->PeerCommonName() == "tnetlib-test-server",
              "client extracted server CN from peer cert");
    }

    client_sess->Close();
    client_io.stop();
    if (client_thread.joinable()) client_thread.join();
    io.stop();
    if (io_thread.joinable()) io_thread.join();
}

// Negative test: client presents no cert (uses a vanilla tls_client
// context with no use_certificate_file). Server requires a cert
// (verify_fail_if_no_peer_cert) — handshake must fail.
void TestTlsHandshakeFailsWithoutClientCert()
{
    std::printf("[TLS handshake rejects missing client cert]\n");

    asio::io_context io;
    auto server_ctx = MakeServerCtx();
    asio::ssl::context bad_client_ctx(asio::ssl::context::tls_client);
    bad_client_ctx.load_verify_file(CertPath("ca.crt"));
    bad_client_ctx.set_verify_mode(asio::ssl::verify_peer);
    // Deliberately do NOT call use_certificate_file / use_private_key_file.

    tcp::acceptor acceptor(io, tcp::endpoint(tcp::v4(), 0));
    const std::uint16_t port = acceptor.local_endpoint().port();

    std::atomic<bool> server_hs_result{true};  // expect false on rejection
    std::atomic<bool> server_done{false};
    asio::co_spawn(io,
        [&]() -> asio::awaitable<void> {
            boost::system::error_code ec;
            auto sock = co_await acceptor.async_accept(
                asio::redirect_error(asio::use_awaitable, ec));
            if (ec) {
                server_done.store(true);
                co_return;
            }
            auto sess = std::make_shared<tnetlib::TlsAsioSession>(
                std::move(sock), server_ctx);
            const bool ok = co_await sess->Handshake(
                tnetlib::TlsRole::Server);
            server_hs_result.store(ok);
            server_done.store(true);
        },
        asio::detached);

    std::thread io_thread([&io] { io.run(); });
    std::this_thread::sleep_for(std::chrono::milliseconds(50));

    asio::io_context client_io;
    tcp::socket client_sock(client_io);
    client_sock.connect(tcp::endpoint(asio::ip::address_v4::loopback(), port));

    auto client_sess = std::make_shared<tnetlib::TlsAsioSession>(
        std::move(client_sock), bad_client_ctx);

    std::atomic<bool> client_hs_result{true};
    std::atomic<bool> client_done{false};
    asio::co_spawn(client_io,
        [client_sess, &client_hs_result, &client_done]()
            -> asio::awaitable<void> {
            const bool ok = co_await client_sess->Handshake(
                tnetlib::TlsRole::Client);
            client_hs_result.store(ok);
            client_done.store(true);
        },
        asio::detached);

    std::thread client_thread([&client_io] { client_io.run(); });

    const auto deadline = std::chrono::steady_clock::now() +
                          std::chrono::seconds(3);
    while ((!server_done.load() || !client_done.load()) &&
           std::chrono::steady_clock::now() < deadline)
    {
        std::this_thread::sleep_for(std::chrono::milliseconds(20));
    }

    // At least one side must have rejected the handshake. (Either:
    // the server detects the missing peer cert during its handshake
    // and fails; the client may then see the TCP close as a
    // handshake failure too. We accept either outcome — the goal is
    // that the connection did NOT come up successfully on both ends.)
    const bool either_failed = !server_hs_result.load() ||
                                !client_hs_result.load();
    Check(either_failed,
          "handshake rejected when client presents no cert");

    client_sess->Close();
    client_io.stop();
    if (client_thread.joinable()) client_thread.join();
    io.stop();
    if (io_thread.joinable()) io_thread.join();
}

} // namespace

int main()
{
    std::printf("=== tnetlib TLS session tests ===\n");
    // Mute default stderr sink so handshake-failure tests don't spam
    // expected diagnostics across the test log.
    tnetlib::AsioSession::SetErrorLogger(nullptr);
    try
    {
        TestTlsPacketRoundtrip();
        TestTlsHandshakeFailsWithoutClientCert();
    }
    catch (const std::exception& ex)
    {
        std::printf("  FAIL  exception thrown: %s\n", ex.what());
        ++g_failed;
    }
    std::printf("\nResults: %d passed, %d failed\n", g_passed, g_failed);
    return g_failed == 0 ? 0 : 1;
}
