


/*
	캐릭터가 현재 보유한 돈에 관련된 통계
*/
CREATE   PROCEDURE BatchSnapshot_Item
	@pWorld INT,			
	@pDate	SMALLDATETIME
AS

	--
	-- Insert Statistic
	--

	DELETE TGLOBAL_GSP.DBO.SDATA160TL WHERE SDATA160_DATE = @pDate AND SDATA160_WORLD = @pWorld

	--
	-- Important
	--
	INSERT INTO TGLOBAL_GSP.DBO.SDATA160TL
	(
		SDATA160_DATE,
		SDATA160_WORLD,
		SDATA160_TYPE,
		SDATA160_ITEMID,
		SDATA160_LEVEL,
		SDATA160_CNT1,
		SDATA160_CNT2
	)
	SELECT 	@pDate,
		@pWorld,
		1,
		wItemID, 
		0,
		COUNT(*),  
		(SELECT  COUNT(*) FROM TITEMTABLE WHERE wItemID = A.wItemID AND bGLevel <> 0)
	FROM	TITEMTABLE A
	WHERE	 wItemID IN ( SELECT 	CODE_VALUE FROM TGLOBAL_GSP.DBO.	SCODETL WHERE	CODE_LARGE ='ITEM' AND CODE_SMALL = 1)
	GROUP	BY wItemID
	ORDER	BY wItemID

	--
	-- Upgrade
	--
	INSERT INTO TGLOBAL_GSP.DBO.SDATA160TL
	(
		SDATA160_DATE,
		SDATA160_WORLD,
		SDATA160_TYPE,
		SDATA160_ITEMID,
		SDATA160_LEVEL,
		SDATA160_CNT1,
		SDATA160_CNT2
	)
	SELECT 	@pDate,
		@pWorld,
		2,
		wItemID, 
		0,
		COUNT(*),  
		0
	FROM	TITEMTABLE A
	WHERE	 wItemID IN ( SELECT 	CODE_VALUE FROM TGLOBAL_GSP.DBO.	SCODETL WHERE	CODE_LARGE ='ITEM' AND CODE_SMALL = 2)
	GROUP	BY wItemID
	ORDER	BY wItemID

	--
	-- Spend Item
	--
	INSERT INTO TGLOBAL_GSP.DBO.SDATA160TL
	(
		SDATA160_DATE,
		SDATA160_WORLD,
		SDATA160_TYPE,
		SDATA160_ITEMID,
		SDATA160_LEVEL,
		SDATA160_CNT1,
		SDATA160_CNT2
	)
	SELECT 	@pDate,
		@pWorld,
		3,
		wItemID, 
		0,
		COUNT(*),  
		0
	FROM	TITEMTABLE A
	WHERE	 wItemID IN ( SELECT 	CODE_VALUE FROM TGLOBAL_GSP.DBO.	SCODETL WHERE	CODE_LARGE ='ITEM' AND CODE_SMALL = 3)
	GROUP	BY wItemID
	ORDER	BY wItemID

	--
	--	CASH
	--
	INSERT INTO TGLOBAL_GSP.DBO.SDATA160TL
	(
		SDATA160_DATE,
		SDATA160_WORLD,
		SDATA160_TYPE,
		SDATA160_ITEMID,
		SDATA160_LEVEL,
		SDATA160_CNT1,
		SDATA160_CNT2
	)
	SELECT 	@pDate,
		@pWorld,
		4,
		wItemID, 
		0,
		COUNT(*),  
		0
	FROM	TITEMTABLE A
	WHERE	 wItemID IN ( SELECT 	CODE_VALUE FROM TGLOBAL_GSP.DBO.	SCODETL WHERE	CODE_LARGE ='ITEM' AND CODE_SMALL = 4)
	GROUP	BY wItemID
	ORDER	BY wItemID

	--
	-- 	GODDESS TEAR
	--
	INSERT INTO TGLOBAL_GSP.DBO.SDATA160TL
	(
		SDATA160_DATE,
		SDATA160_WORLD,
		SDATA160_TYPE,
		SDATA160_ITEMID,
		SDATA160_LEVEL,
		SDATA160_CNT1,
		SDATA160_CNT2
	)
	SELECT 	@pDate,
			@pWorld,
			10,
			wItemID, 
			bGLevel,
			COUNT(*),  
			0
	FROM	TITEMTABLE
	WHERE     wItemID = 6701
	GROUP	BY wItemID, bGLevel
	ORDER	BY bGLevel DESC

	--
	--	UPGRADED ITEM
	--
	INSERT INTO TGLOBAL_GSP.DBO.SDATA160TL
	(
		SDATA160_DATE,
		SDATA160_WORLD,
		SDATA160_TYPE,
		SDATA160_ITEMID,
		SDATA160_LEVEL,
		SDATA160_CNT1,
		SDATA160_CNT2
	)
	SELECT 	@pDate,
			@pWorld,
			11,
			wItemID, 
			bLevel,
			COUNT(*),  
			0
	FROM	TITEMTABLE
	WHERE     bLevel  <> 0
	GROUP	BY wItemID, bLevel

