CREATE PROCEDURE [dbo].[TAddBRPlayer]
@dwCharID INT,
@dwUserID INT
AS

declare @wArmor SMALLINT

IF EXISTS ( SELECT dwUserID FROM TBRPLAYERTABLE WHERE dwCharID = @dwCharID)
BEGIN
	UPDATE TBRPLAYERTABLE SET dwUserID = @dwUserID WHERE dwCharID = @dwCharID
END
ELSE
BEGIN
	INSERT INTO TBRPLAYERTABLE (dwCharID, dwUserID) VALUES (@dwCharID, @dwUserID)
END

