


/* DELETE CHARACTER PROCESS

========================================================
PARAMETER
========================================================
@dwCharID		INT

========================================================
RETURN VALUE
========================================================
0	: SUCCESS
1	: FAIL (Guild)

========================================================
PROCESS
========================================================
1. Delete Character

*/


CREATE PROCEDURE [dbo].[TDeleteChar]
	@bCreateCnt		TINYINT OUTPUT,
	@bGroup		TINYINT,
	@dwUserID		INT,
	@dwCharID		INT
AS
	DECLARE @szNAME VARCHAR(50)
	DECLARE @bLevel TINYINT

	SELECT @bLevel = bLevel, @szNAME = szNAME FROM TCHARTABLE WHERE dwUserID = @dwUserID AND dwCharID = @dwCharID AND bDelete = 0
	IF(@@ROWCOUNT = 0)
		RETURN 1

	SELECT dwCharID FROM TGUILDMEMBERTABLE WHERE dwCharID = @dwCharID
	IF(@@ROWCOUNT != 0)
	BEGIN
		RETURN 1
	END

	IF(@bLevel > 5)
	BEGIN
		UPDATE TCHARTABLE SET bDelete = 1, dDeleteDate = GETDATE() WHERE dwCharID = @dwCharID
		EXEC TGLOBAL_GSP.DBO.TDeleteChar @bGroup, @szNAME, @dwCharID
	END
	ELSE
	BEGIN
		DELETE FROM TPOSTTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TFRIENDTABLE WHERE dwCharID = @dwCharID OR dwFriendID = @dwCharID
		DELETE FROM TFRIENDGROUPTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TPROTECTEDTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TSKILLTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TITEMTABLE WHERE dwOwnerID = @dwCharID AND bOwnerType = 0
		DELETE FROM TINVENTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TCABINETTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TQUESTTERMTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TQUESTTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TRECALLMONTABLE WHERE dwOwnerID = @dwCharID
		DELETE FROM TRECALLMAINTAINTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TSKILLMAINTAINTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TSKILLTABLE WHERE dwCharID = @dwCharID
		DELETE FROM THOTKEYTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TITEMUSEDTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TEXPITEMTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TSOULMATETABLE WHERE dwCharID = @dwCharID OR dwTarget = @dwCharID
		DELETE FROM TCASTLEAPPLICANTTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TDUELCHARTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TDUELSCORETABLE WHERE dwCharID = @dwCharID
		DELETE FROM TPVPOINTTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TPVPRECENTTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TPVPRECORDTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TCHARTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TTEMPINVENTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TTEMPITEMTABLE WHERE dwOwnerID = @dwCharID and bOwnerType=0
		DELETE FROM TTEMPSKILLTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TTEMPEXPITEMTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TTEMPCABINETTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TTEMPITEMUSEDTABLE WHERE dwCharID = @dwCharID
		DELETE FROM TTEMPSKILLMAINTAINTABLE WHERE dwCharID = @dwCharID
	
		IF EXISTS (SELECT * FROM TGLOBAL_GSP.DBO.TALLCHARTABLE WHERE dwCharID=@dwCharID AND bWorldID = @bGroup)
			DELETE FROM TGLOBAL_GSP.DBO.TALLCHARTABLE WHERE dwCharID=@dwCharID AND bWorldID = @bGroup
	END

	SELECT @bCreateCnt = COUNT(*) FROM TCHARTABLE WHERE dwUserID=@dwUserID AND bDelete=0

	RETURN 0

