CREATE PROCEDURE [dbo].[TDeleteCompanion]
@dwCharID INT,
@bSlot TINYINT
AS
IF EXISTS (SELECT dwCharID FROM TCOMPANIONTABLE WHERE dwCharID = @dwCharID)
BEGIN
	BEGIN
	DELETE FROM TCOMPANIONTABLE WHERE dwCharID = @dwCharID AND bSlot = @bSlot
	DELETE FROM TCOMPANIONITEMTABLE WHERE dwCharID = @dwCharID AND bSlot = @bSlot
END
END

