

CREATE PROCEDURE [dbo].[TEraseChar]	
	@dwCharID		INT
AS
	DECLARE @dwUserID INT
	DECLARE @bGroup	TINYINT
	DECLARE @szNAME 	VARCHAR(50)	

--	BEGIN TRAN ERASECHAR
	
	SELECT @dwUserID = dwUserID, @szNAME = szNAME FROM TCHARTABLE WHERE dwCharID = @dwCharID
	IF(@@ROWCOUNT = 0)
	BEGIN
--		COMMIT TRAN ERASECHAR
		RETURN 1
	END

	IF EXISTS (SELECT * FROM TGUILDMEMBERTABLE WHERE dwCharID = @dwCharID AND bDuty=2 )
	BEGIN
--		COMMIT TRAN ERASECHAR
		RETURN 2
	END

	SELECT @bGroup = bWorldID FROM TGLOBAL_GSP.DBO.TALLCHARTABLE WHERE dwCharID = @dwCharID AND szName = @szName
	IF(@@ROWCOUNT = 0 )
	BEGIN
--		COMMIT TRAN ERASECHAR
		RETURN 3
	END

	IF EXISTS ( SELECT * FROM TGLOBAL_GSP.DBO.TCURRENTUSER WHERE bGroupID = @bGroup AND dwCharID = @dwCharID )
	BEGIN	
--		COMMIT TRAN ERASECHAR
		RETURN 4
	END

	DELETE FROM TPOSTTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TFRIENDTABLE WHERE dwCharID = @dwCharID OR dwFriendID = @dwCharID
	DELETE FROM TFRIENDGROUPTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TPROTECTEDTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TSKILLTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TITEMTABLE WHERE dwOwnerID = @dwCharID AND bOwnerType = 0
	DELETE FROM TINVENTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TCABINETTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TQUESTTERMTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TQUESTTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TRECALLMONTABLE WHERE dwOwnerID = @dwCharID
	DELETE FROM TRECALLMAINTAINTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TSKILLMAINTAINTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TSKILLTABLE WHERE dwCharID = @dwCharID
	DELETE FROM THOTKEYTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TITEMUSEDTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TEXPITEMTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TSOULMATETABLE WHERE dwCharID = @dwCharID OR dwTarget = @dwCharID
	DELETE FROM TCHARTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TCASTLEAPPLICANTTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TDUELCHARTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TDUELSCORETABLE WHERE dwCharID = @dwCharID
	DELETE FROM TPVPOINTTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TPVPRECENTTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TPVPRECORDTABLE WHERE dwCharID = @dwCharID

	DELETE FROM TTEMPINVENTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TTEMPITEMTABLE WHERE dwOwnerID = @dwCharID and bOwnerType=0
	DELETE FROM TTEMPSKILLTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TTEMPEXPITEMTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TTEMPCABINETTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TTEMPITEMUSEDTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TTEMPSKILLMAINTAINTABLE WHERE dwCharID = @dwCharID

	DELETE FROM TGUILDMEMBERTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TGUILDTACTICSTABLE WHERE dwCharID = @dwCharID
	DELETE FROM TGUILDVOLUNTEERTABLE WHERE dwCharID = @dwCharID

	DELETE FROM TGLOBAL_GSP.DBO.TALLCHARTABLE WHERE dwCharID=@dwCharID AND bWorldID = @bGroup	
	DELETE FROM TGLOBAL_GSP.DBO.TALLRANKTABLE WHERE dwCharID = @dwCharID AND bWorld = @bGroup
	DELETE FROM TGLOBAL_GSP.DBO.TRESERVEDNAME WHERE szName = @szName

--	COMMIT TRAN ERASECHAR

	RETURN 0


