
/*
	Generater Unique ID
*/
CREATE PROCEDURE [dbo].[TGenerateDBItemID]
	@dlID BIGINT OUTPUT
AS

DECLARE @dlInit BIGINT
DECLARE @dlMax BIGINT

SET @dlInit = POWER(CAST(2 AS BIGINT),56)

IF NOT EXISTS( SELECT * FROM TDBITEMINDEXTABLE WHERE dlID >= bWorld * @dlInit  AND dlID < (bWorld+1) * @dlInit)
BEGIN
	EXEC TInitGenItemID @dlID OUTPUT, 0
	UPDATE TDBITEMINDEXTABLE SET dlID = @dlID
END

BEGIN TRAN CREATE_ITEMID

	UPDATE TDBITEMINDEXTABLE SET dlID = dlID+1

	SELECT TOP 1 @dlID = dlID 
	FROM TDBITEMINDEXTABLE

COMMIT TRAN CREATE_ITEMID


