CREATE PROCEDURE [dbo].[TGetPosition]
@dwCharID INT,
@wMapID SMALLINT OUTPUT,
@fPosX FLOAT OUTPUT,
@fPosY FLOAT OUTPUT,
@fPosZ FLOAT OUTPUT
AS
BEGIN
	SET @wMapID = (SELECT wMapID FROM TCHARTABLE WHERE dwCharID = @dwCharID)
	SET @fPosX = (SELECT fPosX FROM TCHARTABLE WHERE dwCharID = @dwCharID)
	SET @fPosY = (SELECT fPosY FROM TCHARTABLE WHERE dwCharID = @dwCharID)
	SET @fPosZ = (SELECT fPosZ FROM TCHARTABLE WHERE dwCharID = @dwCharID)
END
