


CREATE PROCEDURE [dbo].[TGuildDelete]
@dwGuildID int
AS

/*
SELECT * FROM TGUILDRELATION WHERE dwGuildOne=@dwGuildID OR dwGuildTwo = @dwGuildID
IF(@@ROWCOUNT > 0)
	RETURN 1
*/

BEGIN TRAN GUILD_DELETE
	
	DELETE TGUILDWANTEDTABLE WHERE dwGuildID = @dwGuildID
	DELETE TGUILDTACTICSWANTEDTABLE WHERE dwGuildID = @dwGuildID
	DELETE TGUILDTACTICSTABLE WHERE dwGuildID = @dwGuildID

	DELETE TGUILDARTICLETABLE WHERE dwGuildID = @dwGuildID
	DELETE TGUILDCABINETTABLE WHERE dwGuildID = @dwGuildID
	DELETE TGUILDMEMBERTABLE WHERE dwGuildID = @dwGuildID
	DELETE TGUILDTABLE WHERE dwID = @dwGuildID

COMMIT TRAN GUILD_DELETE



