




CREATE PROCEDURE [dbo].[TSaveCharDataEnd]
@dwCharID INT
AS

DECLARE @dwUserID INT
SELECT @dwUserID = dwUserID FROM TCHARTABLE WHERE dwCharID = @dwCharID

BEGIN TRAN SAVECHAREND

DELETE TINVENTABLE WHERE dwCharID = @dwCharID
DELETE TCABINETTABLE WHERE dwCharID = @dwCharID
/*DELETE TITEMTABLE WHERE dwOwnerID = @dwCharID AND bOwnerType = 0 AND bStorageType <> 2
DELETE TSKILLTABLE WHERE dwCharID = @dwCharID
DELETE TSKILLMAINTAINTABLE WHERE dwCharID = @dwCharID*/
DELETE TITEMUSEDTABLE WHERE dwCharID = @dwCharID
DELETE TEXPITEMTABLE WHERE dwCharID = @dwCharID
/*DELETE TITEMTABLE WHERE dlID IN(SELECT dlID FROM TTEMPITEMTABLE WHERE dwOwnerID = @dwCharID)*/

INSERT INTO TINVENTABLE SELECT * FROM TTEMPINVENTABLE WHERE dwCharID = @dwCharID
INSERT INTO TCABINETTABLE SELECT * FROM TTEMPCABINETTABLE WHERE dwCharID = @dwCharID
/*INSERT INTO TSKILLTABLE SELECT * FROM TTEMPSKILLTABLE WHERE dwCharID = @dwCharID
INSERT INTO TSKILLMAINTAINTABLE SELECT * FROM TTEMPSKILLMAINTAINTABLE WHERE dwCharID = @dwCharID*/
INSERT INTO TITEMUSEDTABLE SELECT * FROM TTEMPITEMUSEDTABLE WHERE dwCharID = @dwCharID
INSERT INTO TEXPITEMTABLE SELECT * FROM TTEMPEXPITEMTABLE WHERE dwCharID = @dwCharID
/*INSERT INTO TITEMTABLE(
	dlID, bStorageType, dwStorageID, bOwnerType, dwOwnerID, bItemID, wItemID, bLevel, bCount, bGLevel, dwDuraMax, dwDuraCur, bRefineCur,dEndTime,bGradeEffect,
	bMagic1, bMagic2, bMagic3, bMagic4, bMagic5, bMagic6,
	wValue1, wValue2, wValue3, wValue4, wValue5, wValue6,
	dwTime1, dwTime2, dwTime3, dwTime4, dwTime5, dwTime6)
	SELECT * FROM TTEMPITEMTABLE WHERE dwOwnerID = @dwCharID*/

COMMIT TRAN SAVECHAREND

EXEC TGLOBAL_GSP.DBO.TSaveDuringItem @dwUserID



