


CREATE PROCEDURE [dbo].[TSaveCharDataStart]
@dwCharID INT
AS

DECLARE @dwUserID INT
SELECT @dwUserID = dwUserID FROM TCHARTABLE WHERE dwCharID = @dwCharID

BEGIN TRAN SAVECHARDATA
DELETE TTEMPINVENTABLE WHERE dwCharID = @dwCharID
DELETE TTEMPCABINETTABLE WHERE dwCharID = @dwCharID
DELETE TTEMPITEMTABLE WHERE dwOwnerID = @dwCharID
DELETE TTEMPSKILLTABLE WHERE dwCharID = @dwCharID
DELETE TTEMPSKILLMAINTAINTABLE WHERE dwCharID = @dwCharID
DELETE TTEMPITEMUSEDTABLE WHERE dwCharID = @dwCharID
DELETE TTEMPEXPITEMTABLE WHERE dwCharID = @dwCharID
COMMIT TRAN SAVECHARDATA

EXEC TGLOBAL_GSP.DBO.TSaveDuringItemStart @dwUserID



