
CREATE PROCEDURE [dbo].[TTnmtEventDel]
@wTourID SMALLINT
AS

DELETE FROM TTNMTEVENTTIMETABLE WHERE wTournamentID=@wTourID
DELETE FROM TTNMTEVENTSCHEDULETABLE WHERE wTournamentID=@wTourID
DELETE FROM TTNMTEVENTTABLE WHERE wTournamentID=@wTourID
DELETE FROM TTNMTEVENTREWARDTABLE WHERE wTournamentID=@wTourID



