


CREATE PROCEDURE [dbo].[TUpdateQuest]
AS

TRUNCATE TABLE  TQCONDITIONCHART
TRUNCATE TABLE  TQUESTTERMCHART
TRUNCATE TABLE  TQREWARDCHART
TRUNCATE TABLE  TQUESTCHART
TRUNCATE TABLE  TQTITLECHART
TRUNCATE TABLE  TQCLASSCHART

INSERT INTO TQUESTCHART SELECT * FROM TQUEST_GSP.DBO.TQUESTCHART
INSERT INTO TQUESTTERMCHART SELECT * FROM TQUEST_GSP.DBO.TQUESTTERMCHART
INSERT INTO TQREWARDCHART SELECT * FROM TQUEST_GSP.DBO.TQREWARDCHART
INSERT INTO TQCONDITIONCHART SELECT * FROM TQUEST_GSP.DBO.TQCONDITIONCHART
INSERT INTO TQTITLECHART (dwQuestID,dwClassID, szTitle, szMessage, szComplete, szAccept, szReject,szSummary,szNPCName,szReply)   SELECT dwQuestID,dwClassID, szTitle, szMessage, szComplete, szAccept, szReject,szSummary,szNPCName,szReply  FROM TQUEST_GSP.DBO.TQTITLECHART
INSERT INTO TQCLASSCHART SELECT * FROM TQUEST_GSP.DBO.TQCLASSCHART


