CREATE PROCEDURE [dbo].[TChangeRace]
@szName VARCHAR(50),
@bRace TINYINT
AS

IF NOT EXISTS(SELECT TOP 1 * FROM TALLCHARTABLE WHERE szName = @szName)
	RETURN 1
IF NOT EXISTS(SELECT TOP 1 * FROM TGAME.DBO.TCHARTABLE WHERE szName = @szName)
	RETURN 1

UPDATE TALLCHARTABLE SET bRace = @bRace WHERE szName = @szName
UPDATE TGAME.DBO.TCHARTABLE SET bRace = @bRace WHERE szName = @szName

