CREATE PROCEDURE [dbo].[TClearAll]
AS

TRUNCATE TABLE IPBLACKLIST_game
TRUNCATE TABLE TALLCHARTABLE
TRUNCATE TABLE TCASHITEMCABINETTABLE
TRUNCATE TABLE TCASHTESTTABLE
TRUNCATE TABLE USERIPLOG
TRUNCATE TABLE TUSERPROTECTED
TRUNCATE TABLE TACCOUNT_PW
TRUNCATE TABLE TALLCHARTABLE_TRIGGER
