CREATE PROCEDURE [dbo].[TDeleteChar]
@bWorld TINYINT,
@szNAME VARCHAR(50),
@dwCharID INT
AS

UPDATE TALLCHARTABLE SET dwCharID = @dwCharID, bDelete = 1, dDeleteDate = GETDATE()  WHERE szNAME=@szNAME

--UPDATE [192.168.1.9,6121].FOURSTORY_OB.FOURSTORY_WEB.USER030TL SET USER030_DELGBN = 1
--	 WHERE USER030_WORLD=@bWorld AND USER030_CHARID = @dwCharID

